[package]
name = "hiper-bridge"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scl-gui-widgets = { path = "../SharpCraftLauncher/scl-gui-widgets" }

druid = { git = "https://github.com/Steve-xmh/druid.git", features = ["im"] }
nom = "^7.1"
oneshot = "0.1.3"
tinyget = { version = "1.0", features = ["https"] }

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "*"
features = [
    "Win32_System_Diagnostics_Debug",
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_ProcessStatus",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
    "Win32_UI_Shell",
]

[target.'cfg(target_os = "windows")'.build-dependencies]
winres = "*"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
debug = false
strip = true
